CREATE TABLE IF NOT EXISTS favorite_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_name TEXT NOT NULL,
    address TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    google_place_id TEXT NOT NULL,
    category TEXT,
    note TEXT,
    visited INTEGER DEFAULT 0,
    revisit_rating INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS place_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_value TEXT NOT NULL UNIQUE,
    category_label TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    is_active INTEGER DEFAULT 1
);

INSERT INTO place_categories (
    category_value,
    category_label,
    sort_order
)
VALUES
    ('cafe', '咖啡廳', 1),
    ('brunch', '早午餐', 2),
    ('dessert', '甜點店', 3),
    ('bistro', '餐酒館', 4),
    ('snack', '小吃店', 5),
    ('restaurant', '餐廳', 6),
    ('bar', '酒吧', 7),
    ('attraction', '景點', 8),
    ('exhibition', '展覽', 9),
    ('shop', '選物店', 10),
    ('stationery', '文具店', 11),
    ('toy', '玩具店', 12),
    ('flower', '花店', 13)
ON CONFLICT (category_value) DO NOTHING;
